import os
from datetime import datetime
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
RESULTS_DIR = os.path.join(PROJECT_ROOT, 'results')
ISTANBUL_HOURLY_CSV = os.path.join(DATA_DIR, 'istanbul_ibb_hourly.csv')
ISTANBUL_DAILY_CSV = os.path.join(DATA_DIR, 'istanbul_ibb_daily.csv')
ISTANBUL_STATIONS_JSON = os.path.join(DATA_DIR, 'istanbul_stations.json')
IBB_BASE_URL = 'https://api.ibb.gov.tr/havakalitesi/OpenDataPortalHandler'
IBB_STATIONS_ENDPOINT = f'{IBB_BASE_URL}/GetAQIStations'
IBB_MEASUREMENTS_ENDPOINT = f'{IBB_BASE_URL}/GetAQIByStationId'
PM10_TO_PM25_FACTOR = 0.65
ISTANBUL_START_DATE = datetime(2020, 1, 1)
ISTANBUL_END_DATE = datetime.now()
IBB_DATETIME_FORMAT = '%d.%m.%Y %H:%M:%S'
(PM25_MIN, PM25_MAX) = (0.0, 250.0)
(PM10_MIN, PM10_MAX) = (0.0, 500.0)
(NO2_MIN, NO2_MAX) = (0.0, 200.0)
ISTANBUL_PARTICULATE_MODE = 'pm10'
OPENAQ_API_KEY_ENV = 'OPENAQ_API_KEY'
OPENAQ_BASE_URL = 'https://api.openaq.org/v3'
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15
MIN_THRESHOLD_GAP = 0.4
MIN_THRESHOLD_GAP_PM10 = 0.22
MODE_SCORE_KAPPA_WEIGHT = 0.65
FACTOR_SCORE_KAPPA_WEIGHT = 0.55
CALIBRATION_FIS_RESOLUTION = 151
FACTOR_SEARCH_RESOLUTION = 101
FACTOR_SEARCH_LOOKUP_GRID = 25
FACTOR_SEARCH_SAMPLE_N = 2000
SKIP_PM10_TO_PM25_FACTOR_WHEN_NATIVE = True
CALIBRATION_LOOKUP_GRID = 41
BIAS_CALIBRATION_SAMPLE_N = 3000
FINAL_LOOKUP_GRID = 101
PREFER_NATIVE_PARTICULATE = True
NATIVE_PM10_SCORE_BONUS = 0.05
MODE_HOLDOUT_RATIO = 0.2
MODE_HOLDOUT_WEIGHT = 0.6
MODE_VAL_WEIGHT = 0.4
ENABLE_VAL_THRESHOLD_REFINE = True
VAL_REFINE_ONLY_PM25 = True

def ensure_data_dir():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(RESULTS_DIR, exist_ok=True)
